DELETE FROM `categories`;

INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin', 'Raylib + Odin', 'group', NULL, 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin', 'Odin', 'category', 'group-raylib-odin', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin-chap-ph-n-1-nh-p-m-n', 'Phần 1: Nhập môn', 'chapter', 'group-raylib-odin-tab-odin', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin-chap-ph-n-2-ctdl-h-m', 'Phần 2: CTDL & Hàm', 'chapter', 'group-raylib-odin-tab-odin', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin-chap-ph-n-3-b-nh-con-tr', 'Phần 3: Bộ nhớ & Con trỏ', 'chapter', 'group-raylib-odin-tab-odin', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin-chap-ph-n-4-n-ng-cao', 'Phần 4: Nâng cao', 'chapter', 'group-raylib-odin-tab-odin', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-odin-chap-ph-n-5-t-ch-c-d-n', 'Phần 5: Tổ chức dự án', 'chapter', 'group-raylib-odin-tab-odin', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-t-i-li-u', 'Tài Liệu', 'category', 'group-raylib-odin', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-t-i-li-u-chap-t-i-li-u-g-c', 'Tài liệu Gốc', 'chapter', 'group-raylib-odin-tab-t-i-li-u', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-tr-nh', 'Lộ Trình', 'category', 'group-raylib-odin', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-tr-nh-chap-l-tr-nh-c-b-n', 'Lộ trình Cơ Bản', 'chapter', 'group-raylib-odin-tab-l-tr-nh', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-tr-nh-chap-l-tr-nh-n-ng-cao', 'Lộ trình Nâng Cao', 'chapter', 'group-raylib-odin-tab-l-tr-nh', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-tr-nh-chap-c-p-chuy-n-gia', 'Cấp độ Chuyên Gia', 'chapter', 'group-raylib-odin-tab-l-tr-nh', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-tr-nh-chap-ngh-thu-t-thi-t-k', 'Nghệ thuật Thiết kế', 'chapter', 'group-raylib-odin-tab-l-tr-nh', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-d-n', 'Dự Án', 'category', 'group-raylib-odin', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-d-n-chap-kh-i-ng-d-n', 'Khởi động Dự án', 'chapter', 'group-raylib-odin-tab-d-n', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-d-n-chap-d-n-t-t-nghi-p-vampire-survivors', 'Dự án Tốt Nghiệp (Vampire Survivors)', 'chapter', 'group-raylib-odin-tab-d-n', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-d-n-chap-th-c-h-nh-n-ng-tr-i-avatar-2d', 'Thực Hành Nông Trại (Avatar 2D)', 'chapter', 'group-raylib-odin-tab-d-n', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d', 'Avatar 2D', 'category', 'group-raylib-odin', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-ph-n-h-1-n-n-t-ng', 'Phân Hệ 1: Nền Tảng', 'chapter', 'group-raylib-odin-tab-avatar-2d', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-ph-n-h-2-tr-ng-tr-t', 'Phân Hệ 2: Trồng Trọt', 'chapter', 'group-raylib-odin-tab-avatar-2d', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-ph-n-h-3-ch-n-nu-i', 'Phân Hệ 3: Chăn Nuôi', 'chapter', 'group-raylib-odin-tab-avatar-2d', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-ph-n-h-4-kinh-t', 'Phân Hệ 4: Kinh Tế', 'chapter', 'group-raylib-odin-tab-avatar-2d', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-ph-n-h-5-6-mmo-polish', 'Phân Hệ 5 & 6: MMO & Polish', 'chapter', 'group-raylib-odin-tab-avatar-2d', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-avatar-2d-chap-c-bi-t', 'Đặc Biệt', 'chapter', 'group-raylib-odin-tab-avatar-2d', 6);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja', 'Ninja', 'category', 'group-raylib-odin', 6);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja-chap-ph-n-1-platformer-2d', 'Phần 1: Platformer 2D', 'chapter', 'group-raylib-odin-tab-ninja', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja-chap-ph-n-2-v-h-c-k-n-ng', 'Phần 2: Võ học & Kỹ năng', 'chapter', 'group-raylib-odin-tab-ninja', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja-chap-ph-n-3-qu-i-v-t-combat', 'Phần 3: Quái vật & Combat', 'chapter', 'group-raylib-odin-tab-ninja', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja-chap-ph-n-4-trang-b-p', 'Phần 4: Trang bị & Đập đồ', 'chapter', 'group-raylib-odin-tab-ninja', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-ninja-chap-ph-n-5-ui-ho-n-thi-n', 'Phần 5: UI & Hoàn thiện', 'chapter', 'group-raylib-odin-tab-ninja', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-k-t-online', 'K.T Online', 'category', 'group-raylib-odin', 7);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-k-t-online-chap-k-thu-t-game-online', 'Kỹ Thuật Game Online', 'chapter', 'group-raylib-odin-tab-k-t-online', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-i-game', 'Lỗi Game', 'category', 'group-raylib-odin', 8);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-i-game-chap-30-v-n-th-c-t-troubleshooting', '30 Vấn Đề Thực Tế (Troubleshooting)', 'chapter', 'group-raylib-odin-tab-l-i-game', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-i-online', 'Lỗi Online', 'category', 'group-raylib-odin', 9);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-raylib-odin-tab-l-i-online-chap-6-l-i-game-online-kinh-i-n', '6 Lỗi Game Online Kinh Điển', 'chapter', 'group-raylib-odin-tab-l-i-online', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js', 'React / Next.js', 'group', NULL, 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js', 'Next.js', 'category', 'group-react-next-js', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js-chap-ph-n-1-nh-p-m-n-kh-i-t-o', 'Phần 1: Nhập Môn & Khởi Tạo', 'chapter', 'group-react-next-js-tab-next-js', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js-chap-ph-n-2-routing-rendering', 'Phần 2: Routing & Rendering', 'chapter', 'group-react-next-js-tab-next-js', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js-chap-ph-n-3-d-li-u-ui', 'Phần 3: Dữ Liệu & UI', 'chapter', 'group-react-next-js-tab-next-js', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js-chap-ph-n-4-backend-b-o-m-t', 'Phần 4: Backend & Bảo Mật', 'chapter', 'group-react-next-js-tab-next-js', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-next-js-chap-ph-n-5-tri-n-khai-t-i-u', 'Phần 5: Triển khai & Tối Ưu', 'chapter', 'group-react-next-js-tab-next-js', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs', 'ReactJS', 'category', 'group-react-next-js', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-1-ki-n-tr-c-t-duy', 'Phần 1: Kiến Trúc & Tư Duy', 'chapter', 'group-react-next-js-tab-reactjs', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-2-qu-n-l-tr-ng-th-i', 'Phần 2: Quản Lý Trạng Thái', 'chapter', 'group-react-next-js-tab-reactjs', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-3-routing-form', 'Phần 3: Routing & Form', 'chapter', 'group-react-next-js-tab-reactjs', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-4-hi-u-n-ng-d-li-u-l-n', 'Phần 4: Hiệu Năng & Dữ Liệu Lớn', 'chapter', 'group-react-next-js-tab-reactjs', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-5-ui-ux-testing', 'Phần 5: UI/UX & Testing', 'chapter', 'group-react-next-js-tab-reactjs', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-6-b-o-m-t-ci-cd', 'Phần 6: Bảo Mật & CI/CD', 'chapter', 'group-react-next-js-tab-reactjs', 6);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-react-next-js-tab-reactjs-chap-ph-n-7-th-c-chi-n-doanh-nghi-p', 'Phần 7: Thực Chiến Doanh Nghiệp', 'chapter', 'group-react-next-js-tab-reactjs', 7);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-solidjs-solidstart', 'SolidJS / SolidStart', 'group', NULL, 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-solidjs-solidstart-tab-solidjs', 'SolidJS', 'category', 'group-solidjs-solidstart', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-solidjs-solidstart-tab-solidjs-chap-kh-a-h-c-solidjs', 'Khóa Học SolidJS', 'chapter', 'group-solidjs-solidstart-tab-solidjs', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-solidjs-solidstart-tab-solidstart', 'SolidStart', 'category', 'group-solidjs-solidstart', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-solidjs-solidstart-tab-solidstart-chap-l-m-ch-meta-framework', 'Làm chủ Meta-Framework', 'chapter', 'group-solidjs-solidstart-tab-solidstart', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d', 'Godot 2D', 'group', NULL, 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-c-b-n', 'Cơ Bản', 'category', 'group-godot-2d', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-c-b-n-chap-gdscript-c-b-n', 'GDScript Cơ Bản', 'chapter', 'group-godot-2d-tab-c-b-n', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-m-u-thi-t-k', 'Mẫu Thiết Kế', 'category', 'group-godot-2d', 2);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-m-u-thi-t-k-chap-godot-khi-l-m-game-gdscript-c', 'Godot Khi Làm Game (GDScript & C#)', 'chapter', 'group-godot-2d-tab-m-u-thi-t-k', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-farmer-game', 'Farmer Game', 'category', 'group-godot-2d', 3);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-farmer-game-chap-tri-n-khai-godot-2d-farmer-game', 'Triển Khai Godot 2D - Farmer Game', 'chapter', 'group-godot-2d-tab-farmer-game', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-n-ng-cao', 'Nâng Cao', 'category', 'group-godot-2d', 4);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-n-ng-cao-chap-godot-n-ng-cao-ui-animation', 'Godot Nâng Cao (UI & Animation)', 'chapter', 'group-godot-2d-tab-n-ng-cao', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-component', 'Component', 'category', 'group-godot-2d', 5);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-component-chap-th-vi-n-component-godot-2d', 'Thư Viện Component (Godot 2D)', 'chapter', 'group-godot-2d-tab-component', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-t-i-n-node', 'Từ điển Node', 'category', 'group-godot-2d', 6);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-t-i-n-node-chap-t-i-n-node-2d', 'Từ điển Node 2D', 'chapter', 'group-godot-2d-tab-t-i-n-node', 1);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-h-m-helper', 'Hàm Helper', 'category', 'group-godot-2d', 7);
INSERT INTO `categories` (`id`, `name`, `type`, `parent_id`, `order_num`) VALUES ('group-godot-2d-tab-h-m-helper-chap-t-i-n-h-m-helper-2d', 'Từ điển Hàm Helper 2D', 'chapter', 'group-godot-2d-tab-h-m-helper', 1);
